sudo: required

language: c

os:
 - linux

compiler:
 - gcc

before_script:
 - ./install-python3.sh > install-python3.log
 - ./install-pip.sh > install-pip.log
 - ./install-meson.sh > install-meson.log
 - ./install-ninja-build.sh > install-ninja-build.log
 - ./install-sodium.sh > install-sodium.log

script:
 - meson builddir
 - ninja -C builddir
 - ninja -C builddir test

matrix:
 - fast_finish: true
