sudo: required

language: c

os:
 - linux

compiler:
 - gcc

before_script:
 - ./install-python3.sh
 - ./install-meson.sh
 - ./install-ninja-build.sh
 - ./install-sodium.sh

script:
 - meson builddir
 - ninja -C builddir
 - ninja -C builddir test

matrix:
 - fast_finish: true
